### ISSUE TITLE
Top bar buttons in share view are wrong positioned

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/gallery#269]
See https://cloud.nextcloud.com/apps/gallery/s/0WDHAi9p5n0JSew:

![screen shot 2017-05-17 at 11 54 23](https://cloud.githubusercontent.com/assets/878997/26148612/96e9073a-3af7-11e7-94cd-f57086cdd538.png)

**Comment by LukasReschke** [comment]
cc @nextcloud/designers

**Comment by pixelipo** [comment]
I had a look at this issue, and I would argue it's a regression from _core_  in [this commit](https://github.com/nextcloud/server/commit/20250925) - container was given an `id` instead of a same-named `class` that it had before.

I don't see why this object should have an `id`, class should suffice. Pull request ready https://github.com/nextcloud/server/pull/5920

There are some other issues there, like Download icon and missing Nextcloud logo (on master) which should be fixed in the app itself

**Comment by pixelipo** [comment]
Not 100% fixed until https://github.com/nextcloud/server/pull/5920 is merged as well...

**Comment by MorrisJobke** [comment]
Backport of server PR: https://github.com/nextcloud/server/pull/6112

**Comment by MorrisJobke** [comment]
Backport of gallery PR: #311
