### ISSUE TITLE
Star (set/clear favourite) in thumbnail and full screen view

### ISSUE THREAD

**Issue by mduller** [nextcloud/gallery#448]
## Feature request

**User type**: Logged-in

**User level**: Beginners

### Description
Add star (favourite) option to Gallery's thumbnail and full screen views.

### Benefit / value
Sorting through photos and marking favourites with the star in thumbnail and full screen views would be much more efficient than the steps required to mark favourite photos today. Today, a user needs to remember the filename and switch back to file list mode, find the file by name and then mark it as favourite (... menu). Then, the user has to switch back to Gallery mode and find the next photo to review. This process repeats for every photo the user wants to mark as favourite.

### Risk / caveats
A potential risk I could see (but unclear if it is an actual problem) is that starring files changes the order (starred files move to the top). In full screen mode, ideally, Gallery still continues with the next picture that followed the current one before it was starred/un-starred. In thumbnails mode, it should not be an issue if the thumbnails get reshuffled right away.

### Sponsorship

**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by ryanjk333** [comment]
The ability to mark an image as a favorite in Gallery view is actually the only feature that's holding me back from using NextCloud for my photography business for sharing images with clients and allowing them to choose their favorites for me to edit.  Would it be possible to add this feature or is it more difficult than it sounds?  I haven't programmed in quite a few years, but I'd help in any way I can...  Thanks!

**Comment by mduller** [comment]
One thing to note - which I wasn't aware of initially - is that favorites are per-user. I.e., if user1 stars 1.jpg and 4.jpg, that is completely independent of user2 starring (or not starring at all) the same files. So in @ryanjk333 's use case, he would at least need to log in himself with the client's user to see what the client starred.

**Comment by ryanjk333** [comment]
Yep, I thought of that as well, and that would be no problem.  For my less tech savy clients, it makes sense for me to set up their account for them and just send them the credentials.  Then we share it.  Pixieset has a nice way of separating the photographer from their clients with a one-to-many relationship, but I wouldn't need all that.  Just a simple way for my clients to favorite photos in gallery view.  And the favorites feature is already implemented in NextCloud...I just need the button available in Gallery view, otherwise it's too cumbersome for my clients.  I already have a server with lots of storage, so I feel that buying a cloud subscription photo gallery product like Pixieset would be a waste of money for me.
I was looking at a couple of self hosted photo gallery applications, but I'd prefer NextCloud as it would also allow me to upload documents that I need the client to read and/or sign (contracts, release forms, etc.).
If a monetary contribution would help, I'd definitely be open to it. ;)

**Comment by skjnldsv** [comment]
Yes for the sidebar, but I think the ui should be clear of any marks to focus on the pictures. @jancborchardt ?

**Comment by jancborchardt** [comment]
Yep, by default the interface should not have anything on top of the photos.

But as shortcuts it would be fine to have things show on hover, like favorites and the menu icon. It doesn’t need to be on touch interfaces as these actions will all be available in the viewer, but as quick ways to favorite and access actions this would be good.

@skjnldsv best check things like Google Photos, macOS Photos, Instagram etc. :)
