### ISSUE TITLE
Move delete button away from close and next to picture name

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/gallery#5]
Any file actions should go next to the file name. Having the delete button next to the close button will result in misclicks.

In fact the delete action should be behind a 3-dot menu ideally (like in Files), but only makes sense when there are multiple other actions, like download.

cc @manishbisht since you added the delete button. Backport-request because this is a big usability issue.

**Comment by oparoz** [comment]
>Any file actions should go next to the file name. Having the delete button next to the close button will result in misclicks.

This won't solve the issue. It will be next to other buttons and mistakes will also happen.

>In fact the delete action should be behind a 3-dot menu ideally (like in Files)

Same problem. People can still accidentally press that button in the list of options shown in the menu.

So, it seems that moving the button isn't the real solution, there are plenty of examples of very popular online gallery software from large companies (Google, Apple, Microsoft) which show the delete button, right next to other actions.

I suggest we go with the Google approach and turn the exit button into a "back" button and move it to the left. It feels right since the user is effectively sent back to where he/she started.

![](https://cloud.githubusercontent.com/assets/878997/9907549/fbc3c49e-5c8f-11e5-959c-cfa1bc76bb20.png)

**Comment by manishbisht** [comment]
> I suggest we go with the Google approach and turn the exit button into a "back" button and move it to the left. It feels right since the user is effectively sent back to where he/she started.
It is good to replace the close/button with the back button.
Also when user click on the delete button we can show the confirmation box about deleting the image. So that mistake can't happen.

**Comment by skjnldsv** [comment]
Superseded by #540
